package e1ap_ies

// DataUsagePerPDUSessionReportSecondaryRATType represents the ASN.1 definition from 9_4_5_Information_Element_Definitions.txt:346
type DataUsagePerPDUSessionReportSecondaryRATType int32

const (
	DataUsagePerPDUSessionReportSecondaryRATType_Present DataUsagePerPDUSessionReportSecondaryRATType = 0
)
