package e1ap_ies

// DataUsagePerPDUSessionReportPDUSessionTimedReportList From: 9_4_5_Information_Element_Definitions.txt:346
type DataUsagePerPDUSessionReportPDUSessionTimedReportList []MRDCDataUsageReportItem
