package e1ap_ies

// DRBsSubjectToCounterCheckListEUTRAN represents the ASN.1 definition from 9_4_5_Information_Element_Definitions.txt:696
// DRBsSubjectToCounterCheckListEUTRAN is a list of DRBsSubjectToCounterCheckItemEUTRAN
type DRBsSubjectToCounterCheckListEUTRAN []DRBsSubjectToCounterCheckItemEUTRAN
