package e1ap_ies

// This file contains constant values extracted from the ASN.1 specification.

// General INTEGER Constants
const (
	Prioritylevel                         int64 = 0
	Maxnooftimeperiods                    int64 = 2
	Maxnoofcellgroups                     int64 = 4
	Maxnoofupparameters                   int64 = 8
	Maxnooftnladdresses                   int64 = 8
	Maxnoofqosparasets                    int64 = 8
	Maxnoofsplmns                         int64 = 12
	Maxnooftlas                           int64 = 16
	Maxnoofgtptlas                        int64 = 16
	Maxnoofmdtplmns                       int64 = 16
	Maxnoofdrbs                           int64 = 32
	Maxnooftnlassociations                int64 = 32
	Maxnoofqosflows                       int64 = 64
	Maxnooferrors                         int64 = 256
	Maxnoofeutranqosparameters            int64 = 256
	Maxnoofngranqosparameters             int64 = 256
	Maxnoofpdusessionresource             int64 = 256
	Maxnoofnrcgi                          int64 = 512
	Maxnoofsliceitems                     int64 = 1024
	Maxprivateies                         int64 = 65535
	Maxprotocolextensions                 int64 = 65535
	Maxprotocolies                        int64 = 65535
	Maxnoofextsliceitems                  int64 = 65535
	Maxnoofindividuale1connectionstoreset int64 = 65536
)

// Procedure Codes
const (
	ProcedureCode_Reset                               = 0
	ProcedureCode_Errorindication                     = 1
	ProcedureCode_Privatemessage                      = 2
	ProcedureCode_GnbCuUpE1setup                      = 3
	ProcedureCode_GnbCuCpE1setup                      = 4
	ProcedureCode_GnbCuUpConfigurationupdate          = 5
	ProcedureCode_GnbCuCpConfigurationupdate          = 6
	ProcedureCode_E1release                           = 7
	ProcedureCode_Bearercontextsetup                  = 8
	ProcedureCode_Bearercontextmodification           = 9
	ProcedureCode_Bearercontextmodificationrequired   = 10
	ProcedureCode_Bearercontextrelease                = 11
	ProcedureCode_Bearercontextreleaserequest         = 12
	ProcedureCode_Bearercontextinactivitynotification = 13
	ProcedureCode_Dldatanotification                  = 14
	ProcedureCode_Datausagereport                     = 15
	ProcedureCode_GnbCuUpCountercheck                 = 16
	ProcedureCode_GnbCuUpStatusindication             = 17
	ProcedureCode_Uldatanotification                  = 18
	ProcedureCode_MrdcDatausagereport                 = 19
	ProcedureCode_Tracestart                          = 20
	ProcedureCode_Deactivatetrace                     = 21
	ProcedureCode_Resourcestatusreportinginitiation   = 22
	ProcedureCode_Resourcestatusreporting             = 23
	ProcedureCode_IabUptnladdressupdate               = 24
	ProcedureCode_Celltraffictrace                    = 25
	ProcedureCode_Earlyforwardingsntransfer           = 26
)

// Protocol IE IDs
const (
	ProtocolIEID_Cause                                      = 0
	ProtocolIEID_Criticalitydiagnostics                     = 1
	ProtocolIEID_GnbCuCpUeE1apId                            = 2
	ProtocolIEID_GnbCuUpUeE1apId                            = 3
	ProtocolIEID_Resettype                                  = 4
	ProtocolIEID_UeAssociatedlogicale1Connectionitem        = 5
	ProtocolIEID_UeAssociatedlogicale1Connectionlistresack  = 6
	ProtocolIEID_GnbCuUpId                                  = 7
	ProtocolIEID_GnbCuUpName                                = 8
	ProtocolIEID_GnbCuCpName                                = 9
	ProtocolIEID_Cnsupport                                  = 10
	ProtocolIEID_Supportedplmns                             = 11
	ProtocolIEID_Timetowait                                 = 12
	ProtocolIEID_Securityinformation                        = 13
	ProtocolIEID_Uedlaggregatemaximumbitrate                = 14
	ProtocolIEID_SystemBearercontextsetuprequest            = 15
	ProtocolIEID_SystemBearercontextsetupresponse           = 16
	ProtocolIEID_Bearercontextstatuschange                  = 17
	ProtocolIEID_SystemBearercontextmodificationrequest     = 18
	ProtocolIEID_SystemBearercontextmodificationresponse    = 19
	ProtocolIEID_SystemBearercontextmodificationconfirm     = 20
	ProtocolIEID_SystemBearercontextmodificationrequired    = 21
	ProtocolIEID_DrbStatusList                              = 22
	ProtocolIEID_Activitynotificationlevel                  = 23
	ProtocolIEID_Activityinformation                        = 24
	ProtocolIEID_DataUsageReportList                        = 25
	ProtocolIEID_NewUlTnlInformationRequired                = 26
	ProtocolIEID_GnbCuCpTnlaToAddList                       = 27
	ProtocolIEID_GnbCuCpTnlaToRemoveList                    = 28
	ProtocolIEID_GnbCuCpTnlaToUpdateList                    = 29
	ProtocolIEID_GnbCuCpTnlaSetupList                       = 30
	ProtocolIEID_GnbCuCpTnlaFailedToSetupList               = 31
	ProtocolIEID_DrbToSetupListEutran                       = 32
	ProtocolIEID_DrbToModifyListEutran                      = 33
	ProtocolIEID_DrbToRemoveListEutran                      = 34
	ProtocolIEID_DrbRequiredToModifyListEutran              = 35
	ProtocolIEID_DrbRequiredToRemoveListEutran              = 36
	ProtocolIEID_DrbSetupListEutran                         = 37
	ProtocolIEID_DrbFailedListEutran                        = 38
	ProtocolIEID_DrbModifiedListEutran                      = 39
	ProtocolIEID_DrbFailedToModifyListEutran                = 40
	ProtocolIEID_DrbConfirmModifiedListEutran               = 41
	ProtocolIEID_PduSessionResourceToSetupList              = 42
	ProtocolIEID_PduSessionResourceToModifyList             = 43
	ProtocolIEID_PduSessionResourceToRemoveList             = 44
	ProtocolIEID_PduSessionResourceRequiredToModifyList     = 45
	ProtocolIEID_PduSessionResourceSetupList                = 46
	ProtocolIEID_PduSessionResourceFailedList               = 47
	ProtocolIEID_PduSessionResourceModifiedList             = 48
	ProtocolIEID_PduSessionResourceFailedToModifyList       = 49
	ProtocolIEID_PduSessionResourceConfirmModifiedList      = 50
	ProtocolIEID_DrbToSetupModListEutran                    = 51
	ProtocolIEID_DrbSetupModListEutran                      = 52
	ProtocolIEID_DrbFailedModListEutran                     = 53
	ProtocolIEID_PduSessionResourceSetupModList             = 54
	ProtocolIEID_PduSessionResourceFailedModList            = 55
	ProtocolIEID_PduSessionResourceToSetupModList           = 56
	ProtocolIEID_Transactionid                              = 57
	ProtocolIEID_ServingPlmn                                = 58
	ProtocolIEID_UeInactivityTimer                          = 59
	ProtocolIEID_SystemGnbCuUpCountercheckrequest           = 60
	ProtocolIEID_DrbsSubjectToCounterCheckListEutran        = 61
	ProtocolIEID_DrbsSubjectToCounterCheckListNgRan         = 62
	ProtocolIEID_Ppi                                        = 63
	ProtocolIEID_GnbCuUpCapacity                            = 64
	ProtocolIEID_GnbCuUpOverloadinformation                 = 65
	ProtocolIEID_Uedlmaximumintegrityprotecteddatarate      = 66
	ProtocolIEID_PduSessionToNotifyList                     = 67
	ProtocolIEID_PduSessionResourceDataUsageList            = 68
	ProtocolIEID_Snssai                                     = 69
	ProtocolIEID_Datadiscardrequired                        = 70
	ProtocolIEID_OldqosflowmapUlendmarkerexpected           = 71
	ProtocolIEID_DrbQos                                     = 72
	ProtocolIEID_GnbCuUpTnlaToRemoveList                    = 73
	ProtocolIEID_EndpointIpAddressAndPort                   = 74
	ProtocolIEID_Tnlassociationtransportlayeraddressgnbcuup = 75
	ProtocolIEID_Ranueid                                    = 76
	ProtocolIEID_GnbDuId                                    = 77
	ProtocolIEID_Commonnetworkinstance                      = 78
	ProtocolIEID_Networkinstance                            = 79
	ProtocolIEID_Qosflowmappingindication                   = 80
	ProtocolIEID_Traceactivation                            = 81
	ProtocolIEID_Traceid                                    = 82
	ProtocolIEID_Subscriberprofileidforrfp                  = 83
	ProtocolIEID_Additionalrrmpriorityindex                 = 84
	ProtocolIEID_Retainabilitymeasurementsinfo              = 85
	ProtocolIEID_TransportLayerAddressInfo                  = 86
	ProtocolIEID_Qosmonitoringrequest                       = 87
	ProtocolIEID_PdcpStatusreportindication                 = 88
	ProtocolIEID_GnbCuCpMeasurementId                       = 89
	ProtocolIEID_GnbCuUpMeasurementId                       = 90
	ProtocolIEID_Registrationrequest                        = 91
	ProtocolIEID_Reportcharacteristics                      = 92
	ProtocolIEID_Reportingperiodicity                       = 93
	ProtocolIEID_TnlAvailablecapacityindicator              = 94
	ProtocolIEID_HwCapacityindicator                        = 95
	ProtocolIEID_Redundantcommonnetworkinstance             = 96
	ProtocolIEID_RedundantNgUlUpTnlInformation              = 97
	ProtocolIEID_RedundantNgDlUpTnlInformation              = 98
	ProtocolIEID_Redundantqosflowindicator                  = 99
	ProtocolIEID_Tsctrafficcharacteristics                  = 100
	ProtocolIEID_Cnpacketdelaybudgetdownlink                = 101
	ProtocolIEID_Cnpacketdelaybudgetuplink                  = 102
	ProtocolIEID_Extendedpacketdelaybudget                  = 103
	ProtocolIEID_Additionalpdcpduplicationinformation       = 104
	ProtocolIEID_Redundantpdusessioninformation             = 105
	ProtocolIEID_RedundantpdusessioninformationUsed         = 106
	ProtocolIEID_QosMappingInformation                      = 107
	ProtocolIEID_Dluptnladdresstoupdatelist                 = 108
	ProtocolIEID_Uluptnladdresstoupdatelist                 = 109
	ProtocolIEID_Npnsupportinfo                             = 110
	ProtocolIEID_Npncontextinfo                             = 111
	ProtocolIEID_Mdtconfiguration                           = 112
	ProtocolIEID_Managementbasedmdtplmnlist                 = 113
	ProtocolIEID_Tracecollectionentityipaddress             = 114
	ProtocolIEID_Privacyindicator                           = 115
	ProtocolIEID_Tracecollectionentityuri                   = 116
	ProtocolIEID_Uriaddress                                 = 117
	ProtocolIEID_EhcParameters                              = 118
	ProtocolIEID_DrbsSubjectToEarlyForwardingList           = 119
	ProtocolIEID_Dapsrequestinfo                            = 120
	ProtocolIEID_Choinitiation                              = 121
	ProtocolIEID_Earlyforwardingcountreq                    = 122
	ProtocolIEID_Earlyforwardingcountinfo                   = 123
	ProtocolIEID_Alternativeqosparasetlist                  = 124
	ProtocolIEID_Extendedslicesupportlist                   = 125
)

