package e1ap_ies

// GNBCUUPCellGroupRelatedConfiguration represents the ASN.1 definition from 9_4_5_Information_Element_Definitions.txt:1086
// GNBCUUPCellGroupRelatedConfiguration is a list of GNBCUUPCellGroupRelatedConfigurationItem
type GNBCUUPCellGroupRelatedConfiguration []GNBCUUPCellGroupRelatedConfigurationItem
