package e1ap_ies

// PDUSessionResourceSetupItemNGDLUPUnchanged represents the ASN.1 definition from 9_4_5_Information_Element_Definitions.txt:1757
type PDUSessionResourceSetupItemNGDLUPUnchanged int32

const (
	PDUSessionResourceSetupItemNGDLUPUnchanged_Present PDUSessionResourceSetupItemNGDLUPUnchanged = 0
)
