package e1ap_ies

// QoSFlowLevelQoSParametersReflectiveQOSIndicator represents the ASN.1 definition from 9_4_5_Information_Element_Definitions.txt:2019
type QoSFlowLevelQoSParametersReflectiveQOSIndicator int32

const (
	QoSFlowLevelQoSParametersReflectiveQOSIndicator_Present QoSFlowLevelQoSParametersReflectiveQOSIndicator = 0
)
