package e1ap_ies

// QoSFlowLevelQoSParametersAdditionalQOSInformation represents the ASN.1 definition from 9_4_5_Information_Element_Definitions.txt:2019
type QoSFlowLevelQoSParametersAdditionalQOSInformation int32

const (
	QoSFlowLevelQoSParametersAdditionalQOSInformation_Present QoSFlowLevelQoSParametersAdditionalQOSInformation = 0
)
