package e1ap_ies

// QOSFlowRemovedItemQOSFlowReleasedInSession represents the ASN.1 definition from 9_4_5_Information_Element_Definitions.txt:2037
type QOSFlowRemovedItemQOSFlowReleasedInSession int32

const (
	QOSFlowRemovedItemQOSFlowReleasedInSession_Present QOSFlowRemovedItemQOSFlowReleasedInSession = 0
)
