package e1ap_ies

// TransportUPLayerAddressesInfoToRemoveList From: 9_4_5_Information_Element_Definitions.txt:2344
type TransportUPLayerAddressesInfoToRemoveList []TransportUPLayerAddressesInfoToRemoveItem
