package e1ap_ies

// TransportUPLayerAddressesInfoToRemoveList represents the ASN.1 definition from 9_4_5_Information_Element_Definitions.txt:2344
// TransportUPLayerAddressesInfoToRemoveList is a list of TransportUPLayerAddressesInfoToRemoveItem
type TransportUPLayerAddressesInfoToRemoveList []TransportUPLayerAddressesInfoToRemoveItem
